-- DELETE FROM localstrings where keycode = '${newPluginName}';
-- INSERT INTO localstrings(keycode, langcode, stringvalue) VALUES ('${newPluginName}', 'it', '');
-- INSERT INTO localstrings(keycode, langcode, stringvalue) VALUES ('${newPluginName}', 'en', '');
-- -- <wp:i18n key="${newPluginName}" />
